-- ── Storage bucket ──────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('syllabi', 'syllabi', false, 20971520, '{application/pdf}')
on conflict (id) do nothing;

-- Storage RLS
drop policy if exists "Group members can upload syllabi" on storage.objects;
create policy "Group members can upload syllabi"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'syllabi'
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = (split_part(name, '/', 1))::bigint
        and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can read syllabus files" on storage.objects;
create policy "Group members can read syllabus files"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'syllabi'
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = (split_part(name, '/', 1))::bigint
        and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can delete syllabus files" on storage.objects;
create policy "Group members can delete syllabus files"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'syllabi'
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = (split_part(name, '/', 1))::bigint
        and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can update syllabus files" on storage.objects;
create policy "Group members can update syllabus files"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'syllabi'
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = (split_part(name, '/', 1))::bigint
        and gm.user_id = auth.uid()
    )
  );

-- ── Syllabi table ────────────────────────────────────────────────────────────
create table if not exists public.syllabi (
  id           bigint generated by default as identity primary key,
  group_id     bigint not null references public.study_groups(id) on delete cascade,
  course_id    bigint not null references public.courses(id) on delete cascade,
  uploaded_by  uuid   not null references public.profiles(id) on delete cascade,
  file_path    text   not null,
  file_name    text   not null,
  parsed_at    timestamptz,
  events_extracted integer not null default 0,
  created_at   timestamptz not null default timezone('utc', now()),
  unique (group_id)
);

alter table public.syllabi enable row level security;

drop policy if exists "Group members can read syllabi" on public.syllabi;
create policy "Group members can read syllabi"
  on public.syllabi for select to authenticated
  using (
    exists (
      select 1 from public.group_memberships gm
      where gm.group_id = syllabi.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can insert syllabi" on public.syllabi;
create policy "Group members can insert syllabi"
  on public.syllabi for insert to authenticated
  with check (
    auth.uid() = uploaded_by
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = syllabi.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can update syllabi" on public.syllabi;
create policy "Group members can update syllabi"
  on public.syllabi for update to authenticated
  using (
    exists (
      select 1 from public.group_memberships gm
      where gm.group_id = syllabi.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can delete syllabi" on public.syllabi;
create policy "Group members can delete syllabi"
  on public.syllabi for delete to authenticated
  using (
    exists (
      select 1 from public.group_memberships gm
      where gm.group_id = syllabi.group_id and gm.user_id = auth.uid()
    )
  );

-- ── Extend assignments table ─────────────────────────────────────────────────
alter table public.assignments
  add column if not exists event_type text not null default 'assignment'
    check (event_type in ('assignment', 'exam', 'quiz', 'other')),
  add column if not exists prep_date  date,
  add column if not exists source     text not null default 'manual'
    check (source in ('manual', 'auto')),
  add column if not exists is_flagged boolean not null default false;

-- Allow any group member to delete auto-generated events (US2: users can remove auto events)
drop policy if exists "Creator can delete assignments" on public.assignments;
create policy "Creator or member can delete assignments"
  on public.assignments for delete to authenticated
  using (
    auth.uid() = created_by
    or (
      source = 'auto'
      and exists (
        select 1 from public.group_memberships gm
        where gm.group_id = assignments.group_id and gm.user_id = auth.uid()
      )
    )
  );

-- Allow group members to update auto-generated events (edit titles/dates)
drop policy if exists "Creator can update assignments" on public.assignments;
create policy "Creator or member can update assignments"
  on public.assignments for update to authenticated
  using (
    auth.uid() = created_by
    or (
      source = 'auto'
      and exists (
        select 1 from public.group_memberships gm
        where gm.group_id = assignments.group_id and gm.user_id = auth.uid()
      )
    )
  );
