create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.study_groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists group_messages_group_created_at_idx
  on public.group_messages (group_id, created_at asc);

alter table public.group_messages enable row level security;

drop policy if exists "Group members can read messages" on public.group_messages;
create policy "Group members can read messages"
  on public.group_messages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.group_memberships gm
      where gm.group_id = group_messages.group_id
        and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can send messages" on public.group_messages;
create policy "Group members can send messages"
  on public.group_messages
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from public.group_memberships gm
      where gm.group_id = group_messages.group_id
        and gm.user_id = auth.uid()
    )
  );

alter publication supabase_realtime add table public.group_messages;
