create table if not exists public.collab_sessions (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.study_groups(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  host_user_id uuid not null references public.profiles(id) on delete cascade,
  work_minutes integer not null check (work_minutes between 1 and 180),
  break_minutes integer not null check (break_minutes between 1 and 60),
  status text not null default 'active' check (status in ('active', 'ended')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  started_at timestamptz,
  ended_at timestamptz,
  current_phase text not null default 'work' check (current_phase in ('work', 'break')),
  phase_started_at timestamptz,
  phase_duration_sec integer,
  is_running boolean not null default false,
  paused_remaining_sec integer,
  active_count integer not null default 0,
  eligible_started_at timestamptz
);

create index if not exists collab_sessions_group_id_idx on public.collab_sessions(group_id);
create index if not exists collab_sessions_status_idx on public.collab_sessions(status);

create table if not exists public.collab_session_participants (
  session_id bigint not null references public.collab_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_active boolean not null default false,
  last_joined_at timestamptz,
  last_left_at timestamptz,
  last_eligible_at timestamptz,
  total_active_seconds integer not null default 0 check (total_active_seconds >= 0),
  total_eligible_seconds integer not null default 0 check (total_eligible_seconds >= 0),
  points_awarded integer not null default 0 check (points_awarded >= 0),
  primary key (session_id, user_id)
);

create index if not exists collab_session_participants_user_id_idx on public.collab_session_participants(user_id);

create table if not exists public.collab_session_invites (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.collab_sessions(id) on delete cascade,
  group_id bigint not null references public.study_groups(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  inviter_user_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (session_id, target_user_id)
);

create index if not exists collab_session_invites_target_idx on public.collab_session_invites(target_user_id);

create table if not exists public.collab_session_milestones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  milestone text not null check (milestone in ('20_hours')),
  awarded_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, course_id, milestone)
);

alter table public.collab_sessions enable row level security;
alter table public.collab_session_participants enable row level security;
alter table public.collab_session_invites enable row level security;
alter table public.collab_session_milestones enable row level security;

drop policy if exists "Group members can read collab sessions" on public.collab_sessions;
create policy "Group members can read collab sessions"
  on public.collab_sessions for select to authenticated
  using (
    exists (
      select 1 from public.group_memberships gm
      where gm.group_id = collab_sessions.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can create collab sessions" on public.collab_sessions;
create policy "Group members can create collab sessions"
  on public.collab_sessions for insert to authenticated
  with check (
    auth.uid() = host_user_id
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = collab_sessions.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Host can update collab sessions" on public.collab_sessions;
create policy "Host can update collab sessions"
  on public.collab_sessions for update to authenticated
  using (auth.uid() = host_user_id);

drop policy if exists "Group members can read collab participants" on public.collab_session_participants;
create policy "Group members can read collab participants"
  on public.collab_session_participants for select to authenticated
  using (
    exists (
      select 1 from public.collab_sessions s
      join public.group_memberships gm on gm.group_id = s.group_id
      where s.id = collab_session_participants.session_id
        and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Users can insert own collab participant row" on public.collab_session_participants;
create policy "Users can insert own collab participant row"
  on public.collab_session_participants for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own collab participant row" on public.collab_session_participants;
create policy "Users can update own collab participant row"
  on public.collab_session_participants for update to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own collab invites" on public.collab_session_invites;
create policy "Users can read own collab invites"
  on public.collab_session_invites for select to authenticated
  using (auth.uid() = target_user_id or auth.uid() = inviter_user_id);

drop policy if exists "Users can insert collab invites" on public.collab_session_invites;
create policy "Users can insert collab invites"
  on public.collab_session_invites for insert to authenticated
  with check (auth.uid() = inviter_user_id);

drop policy if exists "Users can update own collab invites" on public.collab_session_invites;
create policy "Users can update own collab invites"
  on public.collab_session_invites for update to authenticated
  using (auth.uid() = target_user_id or auth.uid() = inviter_user_id);

drop policy if exists "Users can read own collab milestones" on public.collab_session_milestones;
create policy "Users can read own collab milestones"
  on public.collab_session_milestones for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own collab milestones" on public.collab_session_milestones;
create policy "Users can insert own collab milestones"
  on public.collab_session_milestones for insert to authenticated
  with check (auth.uid() = user_id);
