create table if not exists public.point_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  source text not null check (source in ('study', 'collab', 'messages', 'surveys', 'calls', 'milestone')),
  points integer not null check (points >= 0),
  ref_id text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, ref_id)
);

create index if not exists point_events_user_id_idx on public.point_events(user_id);
create index if not exists point_events_course_id_idx on public.point_events(course_id);
create index if not exists point_events_source_idx on public.point_events(source);

alter table public.point_events enable row level security;

drop policy if exists "Users can read own point events" on public.point_events;
create policy "Users can read own point events"
  on public.point_events for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own point events" on public.point_events;
create policy "Users can insert own point events"
  on public.point_events for insert to authenticated
  with check (auth.uid() = user_id);

alter publication supabase_realtime add table public.point_events;
alter publication supabase_realtime add table public.user_course_points;
alter publication supabase_realtime add table public.user_badges;
