-- user_course_points: tracks CCR points per user per course (capped at 1000)
create table if not exists public.user_course_points (
  user_id  uuid   not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id)  on delete cascade,
  points   integer not null default 0 check (points >= 0 and points <= 1000),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, course_id)
);

alter table public.user_course_points enable row level security;

drop policy if exists "Own course points" on public.user_course_points;
create policy "Own course points"
  on public.user_course_points for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Group co-members can read course points" on public.user_course_points;
create policy "Group co-members can read course points"
  on public.user_course_points for select to authenticated
  using (
    exists (
      select 1
      from public.group_memberships gm1
      join public.group_memberships gm2 on gm1.group_id = gm2.group_id
      where gm1.user_id = auth.uid()
        and gm2.user_id = user_course_points.user_id
    )
  );

drop policy if exists "Insert own course points" on public.user_course_points;
create policy "Insert own course points"
  on public.user_course_points for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Update own course points" on public.user_course_points;
create policy "Update own course points"
  on public.user_course_points for update to authenticated
  using (auth.uid() = user_id);


-- user_badges: milestone badges at 250 / 500 / 750 / 1000 pts per course
create table if not exists public.user_badges (
  id        bigint generated by default as identity primary key,
  user_id   uuid   not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id)  on delete cascade,
  badge_level integer not null check (badge_level between 1 and 4),
  earned_at  timestamptz not null default timezone('utc', now()),
  unique (user_id, course_id, badge_level)
);

alter table public.user_badges enable row level security;

drop policy if exists "Own badges" on public.user_badges;
create policy "Own badges"
  on public.user_badges for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Group co-members can read badges" on public.user_badges;
create policy "Group co-members can read badges"
  on public.user_badges for select to authenticated
  using (
    exists (
      select 1
      from public.group_memberships gm1
      join public.group_memberships gm2 on gm1.group_id = gm2.group_id
      where gm1.user_id = auth.uid()
        and gm2.user_id = user_badges.user_id
    )
  );

drop policy if exists "Insert own badges" on public.user_badges;
create policy "Insert own badges"
  on public.user_badges for insert to authenticated
  with check (auth.uid() = user_id);


-- award_course_points: add points (capped at 1000) and auto-grant milestone badges
create or replace function public.award_course_points(
  p_user_id  uuid,
  p_course_id bigint,
  p_points   integer
) returns void language plpgsql security definer as $$
declare
  v_old integer;
  v_new integer;
begin
  insert into public.user_course_points (user_id, course_id, points)
  values (p_user_id, p_course_id, 0)
  on conflict (user_id, course_id) do nothing;

  select points into v_old
  from public.user_course_points
  where user_id = p_user_id and course_id = p_course_id;

  v_new := least(v_old + p_points, 1000);

  update public.user_course_points
  set points = v_new, updated_at = timezone('utc', now())
  where user_id = p_user_id and course_id = p_course_id;

  if v_old < 250  and v_new >= 250  then
    insert into public.user_badges (user_id, course_id, badge_level) values (p_user_id, p_course_id, 1) on conflict do nothing;
  end if;
  if v_old < 500  and v_new >= 500  then
    insert into public.user_badges (user_id, course_id, badge_level) values (p_user_id, p_course_id, 2) on conflict do nothing;
  end if;
  if v_old < 750  and v_new >= 750  then
    insert into public.user_badges (user_id, course_id, badge_level) values (p_user_id, p_course_id, 3) on conflict do nothing;
  end if;
  if v_old < 1000 and v_new >= 1000 then
    insert into public.user_badges (user_id, course_id, badge_level) values (p_user_id, p_course_id, 4) on conflict do nothing;
  end if;
end;
$$;


-- Allow group co-members to read each other's basic profile (BUG4)
drop policy if exists "Group co-members can read profiles" on public.profiles;
create policy "Group co-members can read profiles"
  on public.profiles for select to authenticated
  using (
    auth.uid() = id
    or exists (
      select 1
      from public.group_memberships gm1
      join public.group_memberships gm2 on gm1.group_id = gm2.group_id
      where gm1.user_id = auth.uid()
        and gm2.user_id = profiles.id
    )
  );
