create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  work_minutes integer not null check (work_minutes between 1 and 180),
  break_minutes integer not null check (break_minutes between 1 and 60),
  total_work_minutes integer not null check (total_work_minutes >= 0),
  total_break_minutes integer not null check (total_break_minutes >= 0),
  points_awarded integer not null default 0 check (points_awarded >= 0),
  started_at timestamptz not null,
  ended_at timestamptz not null
);

create index if not exists study_sessions_user_id_idx on public.study_sessions(user_id);
create index if not exists study_sessions_course_id_idx on public.study_sessions(course_id);
create index if not exists study_sessions_ended_at_idx on public.study_sessions(ended_at desc);

alter table public.study_sessions enable row level security;

drop policy if exists "Users can read own study sessions" on public.study_sessions;
create policy "Users can read own study sessions"
  on public.study_sessions for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own study sessions" on public.study_sessions;
create policy "Users can insert own study sessions"
  on public.study_sessions for insert to authenticated
  with check (auth.uid() = user_id);
