create table if not exists public.study_groups (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (id, course_id)
);

create table if not exists public.group_memberships (
  group_id bigint not null,
  course_id bigint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default timezone('utc'::text, now()),
  primary key (group_id, user_id),
  unique (course_id, user_id),
  constraint group_memberships_group_course_fkey
    foreign key (group_id, course_id)
    references public.study_groups(id, course_id)
    on delete cascade
);

create table if not exists public.group_requests (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  requester_user_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  target_group_id bigint references public.study_groups(id) on delete set null,
  request_type text not null check (request_type in ('create_group', 'join_group')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint group_requests_requester_target_check check (requester_user_id <> target_user_id),
  constraint group_requests_target_group_required_check check (
    (request_type = 'join_group' and target_group_id is not null)
    or (request_type = 'create_group' and target_group_id is null)
  )
);

create unique index if not exists group_requests_pending_dedupe_idx
  on public.group_requests (course_id, requester_user_id, target_user_id, request_type)
  where status = 'pending';

create index if not exists study_groups_course_id_idx
  on public.study_groups (course_id);

create index if not exists group_memberships_course_id_idx
  on public.group_memberships (course_id);

create index if not exists group_requests_course_id_idx
  on public.group_requests (course_id);

alter table public.study_groups enable row level security;
alter table public.group_memberships enable row level security;
alter table public.group_requests enable row level security;

drop policy if exists "Users in a course can read study groups" on public.study_groups;
create policy "Users in a course can read study groups"
  on public.study_groups
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.course_enrollments as mine
      where mine.user_id = auth.uid()
        and mine.course_id = study_groups.course_id
    )
  );

drop policy if exists "Users can create own study groups" on public.study_groups;
create policy "Users can create own study groups"
  on public.study_groups
  for insert
  to authenticated
  with check (
    auth.uid() = created_by
    and exists (
      select 1
      from public.course_enrollments as mine
      where mine.user_id = auth.uid()
        and mine.course_id = study_groups.course_id
    )
  );

drop policy if exists "Users in a course can read group memberships" on public.group_memberships;
create policy "Users in a course can read group memberships"
  on public.group_memberships
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.course_enrollments as mine
      where mine.user_id = auth.uid()
        and mine.course_id = group_memberships.course_id
    )
  );

drop policy if exists "Users can create own group memberships" on public.group_memberships;
create policy "Users can create own group memberships"
  on public.group_memberships
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can read relevant group requests" on public.group_requests;
create policy "Users can read relevant group requests"
  on public.group_requests
  for select
  to authenticated
  using (auth.uid() = requester_user_id or auth.uid() = target_user_id);

drop policy if exists "Users can create own group requests" on public.group_requests;
create policy "Users can create own group requests"
  on public.group_requests
  for insert
  to authenticated
  with check (
    auth.uid() = requester_user_id
    and exists (
      select 1
      from public.course_enrollments as mine
      where mine.user_id = requester_user_id
        and mine.course_id = group_requests.course_id
    )
    and exists (
      select 1
      from public.course_enrollments as theirs
      where theirs.user_id = target_user_id
        and theirs.course_id = group_requests.course_id
    )
  );

drop policy if exists "Targets can update request status" on public.group_requests;
create policy "Targets can update request status"
  on public.group_requests
  for update
  to authenticated
  using (auth.uid() = target_user_id)
  with check (auth.uid() = target_user_id);
