create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  group_id bigint not null references public.study_groups(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  due_date date,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.assignment_progress (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  progress integer not null default 0 check (progress between 0 and 100),
  note text check (note is null or char_length(note) <= 500),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (assignment_id, user_id)
);

create index if not exists assignments_group_id_idx on public.assignments(group_id);
create index if not exists assignment_progress_assignment_id_idx on public.assignment_progress(assignment_id);

alter table public.assignments enable row level security;
alter table public.assignment_progress enable row level security;

drop policy if exists "Group members can read assignments" on public.assignments;
create policy "Group members can read assignments"
  on public.assignments for select to authenticated
  using (
    exists (
      select 1 from public.group_memberships gm
      where gm.group_id = assignments.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Group members can create assignments" on public.assignments;
create policy "Group members can create assignments"
  on public.assignments for insert to authenticated
  with check (
    auth.uid() = created_by
    and exists (
      select 1 from public.group_memberships gm
      where gm.group_id = assignments.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Creator can update assignments" on public.assignments;
create policy "Creator can update assignments"
  on public.assignments for update to authenticated
  using (auth.uid() = created_by);

drop policy if exists "Creator can delete assignments" on public.assignments;
create policy "Creator can delete assignments"
  on public.assignments for delete to authenticated
  using (auth.uid() = created_by);

drop policy if exists "Group members can read progress" on public.assignment_progress;
create policy "Group members can read progress"
  on public.assignment_progress for select to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.assignments a
      join public.group_memberships gm on gm.group_id = a.group_id
      where a.id = assignment_progress.assignment_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Users can insert own progress" on public.assignment_progress;
create policy "Users can insert own progress"
  on public.assignment_progress for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own progress" on public.assignment_progress;
create policy "Users can update own progress"
  on public.assignment_progress for update to authenticated
  using (auth.uid() = user_id);
